//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capsulas
    {
        public Capsulas()
        {
            this.CapsulasItems = new HashSet<CapsulasItems>();
        }
    
        public string IdCapsula { get; set; }
        public string Descripcion { get; set; }
        public string IdUsuario { get; set; }
        public string ItemID { get; set; }
    
        public virtual ICollection<CapsulasItems> CapsulasItems { get; set; }
    }
}
