//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiInventario
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InventarioEntities : DbContext
    {
        public InventarioEntities()
            : base("name=InventarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Capsules> Capsules { get; set; }
        public virtual DbSet<Inventories> Inventories { get; set; }
        public virtual DbSet<InventoriesItems> InventoriesItems { get; set; }
        public virtual DbSet<CapsulesItems> CapsulesItems { get; set; }
        public virtual DbSet<Spawns> Spawns { get; set; }
        public virtual DbSet<SpawnsCapsules> SpawnsCapsules { get; set; }
        public virtual DbSet<SpawnsCapsulesItems> SpawnsCapsulesItems { get; set; }
    }
}
