//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reproducciones
    {
        public Reproducciones()
        {
            this.ReproduccionesItems = new HashSet<ReproduccionesItems>();
        }
    
        public int IdReproduccion { get; set; }
        public string IdCapsula { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual ICollection<ReproduccionesItems> ReproduccionesItems { get; set; }
    }
}
