//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiInventario
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpawnsCapsules
    {
        public SpawnsCapsules()
        {
            this.SpawnsCapsulesItems = new HashSet<SpawnsCapsulesItems>();
        }
    
        public int SpawnId { get; set; }
        public string CapsuleCode { get; set; }
    
        public virtual Spawns Spawns { get; set; }
        public virtual ICollection<SpawnsCapsulesItems> SpawnsCapsulesItems { get; set; }
    }
}
