//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (empty).
        /// </summary>
        internal static string Capsule_Empty {
            get {
                return ResourceManager.GetString("Capsule_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MMM-dd.
        /// </summary>
        internal static string InterestsByDate_DateFormat_Day {
            get {
                return ResourceManager.GetString("InterestsByDate_DateFormat_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MMM.
        /// </summary>
        internal static string InterestsByDate_DateFormat_Month {
            get {
                return ResourceManager.GetString("InterestsByDate_DateFormat_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MMM-dd.
        /// </summary>
        internal static string InterestsByDate_DateFormat_Week {
            get {
                return ResourceManager.GetString("InterestsByDate_DateFormat_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy.
        /// </summary>
        internal static string InterestsByDate_DateFormat_Year {
            get {
                return ResourceManager.GetString("InterestsByDate_DateFormat_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest by Day.
        /// </summary>
        internal static string InterestsByDate_Title_Day {
            get {
                return ResourceManager.GetString("InterestsByDate_Title_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest by Month.
        /// </summary>
        internal static string InterestsByDate_Title_Month {
            get {
                return ResourceManager.GetString("InterestsByDate_Title_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest by Week.
        /// </summary>
        internal static string InterestsByDate_Title_Week {
            get {
                return ResourceManager.GetString("InterestsByDate_Title_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest by Year.
        /// </summary>
        internal static string InterestsByDate_Title_Year {
            get {
                return ResourceManager.GetString("InterestsByDate_Title_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MMM-dd.
        /// </summary>
        internal static string InterestsChart_DateFormat_Day {
            get {
                return ResourceManager.GetString("InterestsChart_DateFormat_Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MMM.
        /// </summary>
        internal static string InterestsChart_DateFormat_Month {
            get {
                return ResourceManager.GetString("InterestsChart_DateFormat_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MMM-dd.
        /// </summary>
        internal static string InterestsChart_DateFormat_Week {
            get {
                return ResourceManager.GetString("InterestsChart_DateFormat_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy.
        /// </summary>
        internal static string InterestsChart_DateFormat_Year {
            get {
                return ResourceManager.GetString("InterestsChart_DateFormat_Year", resourceCulture);
            }
        }
    }
}
