//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemsNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemsNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ItemsNames", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADA Refactor.
        /// </summary>
        internal static string ADA {
            get {
                return ResourceManager.GetString("ADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capsule MUFG.
        /// </summary>
        internal static string CAPS_MUFG {
            get {
                return ResourceManager.GetString("CAPS_MUFG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Amp.
        /// </summary>
        internal static string FA_RA {
            get {
                return ResourceManager.GetString("FA_RA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jarvis Virus.
        /// </summary>
        internal static string JARVIS {
            get {
                return ResourceManager.GetString("JARVIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra SoftBank Link.
        /// </summary>
        internal static string LA_SB {
            get {
                return ResourceManager.GetString("LA_SB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AXA Shield.
        /// </summary>
        internal static string SHIELD_AXA {
            get {
                return ResourceManager.GetString("SHIELD_AXA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turret.
        /// </summary>
        internal static string TU_RA {
            get {
                return ResourceManager.GetString("TU_RA", resourceCulture);
            }
        }
    }
}
