//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Types {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Types() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Types", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        internal static string T_ATTACK {
            get {
                return ResourceManager.GetString("T_ATTACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capsule.
        /// </summary>
        internal static string T_CAPS {
            get {
                return ResourceManager.GetString("T_CAPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Cube.
        /// </summary>
        internal static string T_CUBES {
            get {
                return ResourceManager.GetString("T_CUBES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Sink.
        /// </summary>
        internal static string T_HSS {
            get {
                return ResourceManager.GetString("T_HSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal Key.
        /// </summary>
        internal static string T_KEYS {
            get {
                return ResourceManager.GetString("T_KEYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Amp.
        /// </summary>
        internal static string T_LAS {
            get {
                return ResourceManager.GetString("T_LAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        internal static string T_MEDIAS {
            get {
                return ResourceManager.GetString("T_MEDIAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-hack.
        /// </summary>
        internal static string T_MHS {
            get {
                return ResourceManager.GetString("T_MHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resonator.
        /// </summary>
        internal static string T_RESOS {
            get {
                return ResourceManager.GetString("T_RESOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield.
        /// </summary>
        internal static string T_SHIELDS {
            get {
                return ResourceManager.GetString("T_SHIELDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra Strike.
        /// </summary>
        internal static string T_USS {
            get {
                return ResourceManager.GetString("T_USS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virus.
        /// </summary>
        internal static string T_VIRUS {
            get {
                return ResourceManager.GetString("T_VIRUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XMP Burster.
        /// </summary>
        internal static string T_XMPS {
            get {
                return ResourceManager.GetString("T_XMPS", resourceCulture);
            }
        }
    }
}
