//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiInventario2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapsulasItems
    {
        public string IdCapsula { get; set; }
        public int IdItem { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Capsulas Capsulas { get; set; }
        public virtual Items Items { get; set; }
    }
}
