//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiInventario2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Items
    {
        public Items()
        {
            this.CapsulasItems = new HashSet<CapsulasItems>();
            this.Inventarios = new HashSet<Inventarios>();
            this.ReproduccionesItems = new HashSet<ReproduccionesItems>();
            this.Capsulas = new HashSet<Capsulas>();
        }
    
        public int IdItem { get; set; }
        public int IdTipo { get; set; }
        public string Nombre { get; set; }
        public int IdNivel { get; set; }
        public int IdRareza { get; set; }
        public Nullable<int> IdImagen { get; set; }
    
        public virtual ICollection<CapsulasItems> CapsulasItems { get; set; }
        public virtual Imagenes Imagenes { get; set; }
        public virtual ICollection<Inventarios> Inventarios { get; set; }
        public virtual Niveles Niveles { get; set; }
        public virtual Rarezas Rarezas { get; set; }
        public virtual Tipos Tipos { get; set; }
        public virtual ICollection<ReproduccionesItems> ReproduccionesItems { get; set; }
        public virtual ICollection<Capsulas> Capsulas { get; set; }
    }
}
