//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiInventario2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipos
    {
        public Tipos()
        {
            this.Items = new HashSet<Items>();
        }
    
        public int IdTipo { get; set; }
        public int IdGrupo { get; set; }
        public string Descripcion { get; set; }
        public bool MostrarNivel { get; set; }
        public bool MostrarRareza { get; set; }
    
        public virtual Grupos Grupos { get; set; }
        public virtual ICollection<Items> Items { get; set; }
    }
}
