//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capsules
    {
        public Capsules()
        {
            this.CapsulesItems = new HashSet<CapsulesItems>();
        }
    
        public int CapsuleId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string UserId { get; set; }
        public string ItemId { get; set; }
    
        public virtual ICollection<CapsulesItems> CapsulesItems { get; set; }
    }
}
