//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class Spawns
    {
        public Spawns()
        {
            this.SpawnsCapsules = new HashSet<SpawnsCapsules>();
        }
    
        public int SpawnId { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ICollection<SpawnsCapsules> SpawnsCapsules { get; set; }
    }
}
