//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpawnsCapsulesItems
    {
        public int SpawnId { get; set; }
        public string CapsuleCode { get; set; }
        public string ItemId { get; set; }
        public int Quantity { get; set; }
    
        public virtual SpawnsCapsules SpawnsCapsules { get; set; }
    }
}
